.TH "core.c" 3 "Thu Jan 19 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core.c
.SH SYNOPSIS
.br
.PP
\fC#include 'iom128v\&.h'\fP
.br
\fC#include 'TO_var\&.h'\fP
.br
\fC#include 'TO\&.h'\fP
.br
\fC#include 'TO_s\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_core_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _core_"

.PP
Definition at line \fB6\fP of file \fBcore\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void main (void)"

.PP
Definition at line \fB13\fP of file \fBcore\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
