.TH "Isr.c" 3 "Thu Jan 19 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Isr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'iom128v\&.h'\fP
.br
\fC#include 'TO_var\&.h'\fP
.br
\fC#include 'TO\&.h'\fP
.br
\fC#include 'TO_s\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBisr_int0\fP (void)"
.br
.ti -1c
.RI "void \fBisr_int1\fP (void)"
.br
.ti -1c
.RI "void \fBisr_int4\fP (void)"
.br
.ti -1c
.RI "void \fBisr_int5\fP (void)"
.br
.ti -1c
.RI "void \fBisr_int6\fP (void)"
.br
.ti -1c
.RI "void \fBisr_int7\fP (void)"
.br
.ti -1c
.RI "void \fBisr_t1_compB\fP (void)"
.br
.ti -1c
.RI "void \fBuart1_rx\fP (void)"
.br
.ti -1c
.RI "void \fBuart1_tx_end\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void isr_int0 (void)"

.PP
Definition at line \fB19\fP of file \fBIsr\&.c\fP\&.
.SS "void isr_int1 (void)"

.PP
Definition at line \fB23\fP of file \fBIsr\&.c\fP\&.
.SS "void isr_int4 (void)"

.PP
Definition at line \fB27\fP of file \fBIsr\&.c\fP\&.
.SS "void isr_int5 (void)"

.PP
Definition at line \fB31\fP of file \fBIsr\&.c\fP\&.
.SS "void isr_int6 (void)"

.PP
Definition at line \fB35\fP of file \fBIsr\&.c\fP\&.
.SS "void isr_int7 (void)"

.PP
Definition at line \fB39\fP of file \fBIsr\&.c\fP\&.
.SS "void isr_t1_compB (void)"

.PP
Definition at line \fB44\fP of file \fBIsr\&.c\fP\&.
.SS "void uart1_rx (void)"

.PP
Definition at line \fB48\fP of file \fBIsr\&.c\fP\&.
.SS "void uart1_tx_end (void)"

.PP
Definition at line \fB52\fP of file \fBIsr\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
