.TH "TO_Init.c" 3 "Thu Jan 19 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TO_Init.c
.SH SYNOPSIS
.br
.PP
\fC#include 'iom128v\&.h'\fP
.br
\fC#include 'TO_var\&.h'\fP
.br
\fC#include 'TO\&.h'\fP
.br
\fC#include 'TO_s\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTO_init\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned char \fBHeader\fP [] ={0x54,0x4f,0x20,0x76,0x31,0x5f,0x34,0x20}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void TO_init (void)"

.PP
Definition at line \fB48\fP of file \fBTO_Init\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const unsigned char Header[] ={0x54,0x4f,0x20,0x76,0x31,0x5f,0x34,0x20}"

.PP
Definition at line \fB14\fP of file \fBTO_Init\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
