.TH "TO_s.h" 3 "Thu Jan 19 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TO_s.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBkeyboard\fP (char n_row)"
.br
.ti -1c
.RI "void \fBscan_key\fP (void)"
.br
.ti -1c
.RI "void \fBset_byte_scan\fP (void)"
.br
.ti -1c
.RI "void \fBbounce_contact\fP (void)"
.br
.ti -1c
.RI "void \fBtransform_code\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_init\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_clr\fP (void)"
.br
.ti -1c
.RI "void \fBcursor_on\fP (void)"
.br
.ti -1c
.RI "void \fBcursor_off\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_wr_com\fP (char data)"
.br
.ti -1c
.RI "void \fBlcd_wr_data\fP (char data)"
.br
.ti -1c
.RI "void \fBlcd_addr_set\fP (char data)"
.br
.ti -1c
.RI "void \fBlcd_2digit\fP (char addr, char data)"
.br
.ti -1c
.RI "void \fBlcd_digit_A\fP (char addr, char data)"
.br
.ti -1c
.RI "void \fBlcd_digit\fP (char data)"
.br
.ti -1c
.RI "void \fBlcd_symbol\fP (char data)"
.br
.ti -1c
.RI "void \fBlcd_delay\fP (void)"
.br
.ti -1c
.RI "void \fBset_addr\fP (char addr)"
.br
.ti -1c
.RI "void \fBshift_byte_D5\fP (void)"
.br
.ti -1c
.RI "void \fBprog_gain\fP (char buf1, char buf2)"
.br
.ti -1c
.RI "void \fBdtmf_wr\fP (char val)"
.br
.ti -1c
.RI "void \fBdtmf_wr_data\fP (char val)"
.br
.ti -1c
.RI "char \fBdtmf_rd\fP (void)"
.br
.ti -1c
.RI "char \fBdtmf_rd_data\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bounce_contact (void)"

.SS "void cursor_off (void)"

.SS "void cursor_on (void)"

.SS "char dtmf_rd (void)"

.SS "char dtmf_rd_data (void)"

.SS "void dtmf_wr (char val)"

.SS "void dtmf_wr_data (char val)"

.SS "char keyboard (char n_row)"

.SS "void lcd_2digit (char addr, char data)"

.SS "void lcd_addr_set (char data)"

.SS "void lcd_clr (void)"

.SS "void lcd_delay (void)"

.SS "void lcd_digit (char data)"

.SS "void lcd_digit_A (char addr, char data)"

.SS "void lcd_init (void)"

.SS "void lcd_symbol (char data)"

.SS "void lcd_wr_com (char data)"

.SS "void lcd_wr_data (char data)"

.SS "void prog_gain (char buf1, char buf2)"

.SS "void scan_key (void)"

.SS "void set_addr (char addr)"

.SS "void set_byte_scan (void)"

.SS "void shift_byte_D5 (void)"

.SS "void transform_code (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
