.TH "TO_var.h" 3 "Thu Jan 19 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TO_var.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRTC_CR\fP   0x8F"
.br
.ti -1c
.RI "#define \fBRTC_Charger\fP   0x91"
.br
.ti -1c
.RI "#define \fBAddr_TO_eep\fP   0x07"
.br
.ti -1c
.RI "#define \fBSP_Mk_eep\fP   0x08"
.br
.ti -1c
.RI "#define \fBIn_PGA_eep\fP   0x09"
.br
.ti -1c
.RI "#define \fBOut_PGA_eep\fP   0x0a"
.br
.ti -1c
.RI "#define \fBTA_Mk_eep\fP   0x0b"
.br
.ti -1c
.RI "#define \fBTA_D_eep\fP   0x0c"
.br
.ti -1c
.RI "#define \fBreg_SP_eep\fP   0x10"
.br
.ti -1c
.RI "#define \fBSign_TA_eep\fP   0x20"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBAddr_TO\fP"
.br
.ti -1c
.RI "char \fBFlag_rc_TO\fP"
.br
.ti -1c
.RI "char \fBN_call\fP"
.br
.ti -1c
.RI "char \fBQnt_TA\fP"
.br
.ti -1c
.RI "char \fBSign_filling\fP"
.br
.ti -1c
.RI "char \fBCnt_pulse\fP"
.br
.ti -1c
.RI "char \fBFlag_ring\fP"
.br
.ti -1c
.RI "char \fBFlag_config\fP"
.br
.ti -1c
.RI "char \fBFlag_key\fP"
.br
.ti -1c
.RI "char \fBFlag_TA_D\fP"
.br
.ti -1c
.RI "char \fBFlag_compB\fP"
.br
.ti -1c
.RI "char \fBCnt_tr_uart\fP"
.br
.ti -1c
.RI "char \fBFlag_TA_TO\fP"
.br
.ti -1c
.RI "char \fBFlag_TO_TA\fP"
.br
.ti -1c
.RI "char \fBStatus_TA\fP"
.br
.ti -1c
.RI "char \fBFlag_1s\fP"
.br
.ti -1c
.RI "char \fBFlag_15s\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Addr_TO_eep   0x07"

.PP
Definition at line \fB31\fP of file \fBTO_var\&.h\fP\&.
.SS "#define In_PGA_eep   0x09"

.PP
Definition at line \fB33\fP of file \fBTO_var\&.h\fP\&.
.SS "#define Out_PGA_eep   0x0a"

.PP
Definition at line \fB34\fP of file \fBTO_var\&.h\fP\&.
.SS "#define reg_SP_eep   0x10"

.PP
Definition at line \fB37\fP of file \fBTO_var\&.h\fP\&.
.SS "#define RTC_Charger   0x91"

.PP
Definition at line \fB30\fP of file \fBTO_var\&.h\fP\&.
.SS "#define RTC_CR   0x8F"

.PP
Definition at line \fB29\fP of file \fBTO_var\&.h\fP\&.
.SS "#define Sign_TA_eep   0x20"

.PP
Definition at line \fB38\fP of file \fBTO_var\&.h\fP\&.
.SS "#define SP_Mk_eep   0x08"

.PP
Definition at line \fB32\fP of file \fBTO_var\&.h\fP\&.
.SS "#define TA_D_eep   0x0c"

.PP
Definition at line \fB36\fP of file \fBTO_var\&.h\fP\&.
.SS "#define TA_Mk_eep   0x0b"

.PP
Definition at line \fB35\fP of file \fBTO_var\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char Addr_TO\fC [extern]\fP"

.SS "char Cnt_pulse"

.PP
Definition at line \fB14\fP of file \fBTO_var\&.h\fP\&.
.SS "char Cnt_tr_uart"

.PP
Definition at line \fB20\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_15s"

.PP
Definition at line \fB25\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_1s"

.PP
Definition at line \fB24\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_compB"

.PP
Definition at line \fB19\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_config"

.PP
Definition at line \fB16\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_key"

.PP
Definition at line \fB17\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_rc_TO"

.PP
Definition at line \fB10\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_ring"

.PP
Definition at line \fB15\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_TA_D"

.PP
Definition at line \fB18\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_TA_TO"

.PP
Definition at line \fB21\fP of file \fBTO_var\&.h\fP\&.
.SS "char Flag_TO_TA"

.PP
Definition at line \fB22\fP of file \fBTO_var\&.h\fP\&.
.SS "char N_call"

.PP
Definition at line \fB11\fP of file \fBTO_var\&.h\fP\&.
.SS "char Qnt_TA"

.PP
Definition at line \fB12\fP of file \fBTO_var\&.h\fP\&.
.SS "char Sign_filling"

.PP
Definition at line \fB13\fP of file \fBTO_var\&.h\fP\&.
.SS "char Status_TA"

.PP
Definition at line \fB23\fP of file \fBTO_var\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
